name: Terraform Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out terraform.tfplan

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v2
      with:
        name: terraform-plan
        path: terraform.tfplan

    #- name: Request Review
    #  uses: actions/github-script@v7
    #  with:
    #    github-token: ${{ secrets.GITHUB_TOKEN }}
    #    script: |
    #      const response = await github.pulls.createReviewRequest({
    #        owner: context.repo.owner,
    #        repo: context.repo.repo,
    #        pull_number: context.payload.pull_request.number,
    #        reviewers: ["cgiacomini"],
    #        files: ["terraform.tfplan"]
    #      });
    #      console.log(response);
    - name: Request Pull Request Review
      run: |
        const { Octokit } = require('@octokit/rest');

        const octokit = new Octokit({
          auth: process.env.GITHUB_TOKEN,
        });

        octokit.pulls.createReviewRequest({
          owner: process.env.GITHUB_REPOSITORY_OWNER,
          repo: process.env.GITHUB_REPOSITORY,
          pull_number: process.env.GITHUB_PULL_REQUEST_NUMBER,
          reviewers: ["reviewer1", "reviewer2"],
          team_reviewers: ["team1"],
          files: ["terraform.tfplan"]
        });
