name: Terraform Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out terraform.tfplan

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v2
      with:
        name: terraform-plan
        path: terraform.tfplan

  request-review:
    runs-on: ubuntu-latest

    needs: terraform-plan

    steps:
    - name: Request Pull Request Review
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.pulls.createReviewRequest({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            reviewers: ["reviewer1", "reviewer2"]
          });

  terraform-apply:
    runs-on: ubuntu-latest

    needs: request-review
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Download Terraform Plan
      uses: actions/download-artifact@v2
      with:
        name: terraform-plan

    - name: Terraform Apply
      run: terraform apply terraform.tfplan
      env:
        TF_VAR_some_variable: ${{ secrets.TF_VAR_SOME_VARIABLE }}

